# Generated by Django 5.1.4 on 2025-01-11 22:22

import django.core.validators
import linguist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('th', 'Thai')], max_length=2)),
                ('file', models.FileField(upload_to='audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3']), linguist.models.audio_file_size])),
                ('correspondent_text', models.TextField(blank=True, null=True)),
                ('correspondent_language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('th', 'Thai')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_audios', models.ManyToManyField(blank=True, related_name='related_to', to='linguist.audio')),
            ],
        ),
    ]
